name: Terraform_Init_And_Plan
on: [push]
# defaults:
#   run:
#     working-directory: ./lz01

permissions: 
  id-token: write
  contents: read
  deployments: write

jobs:
  
  configure-env01:
    runs-on: ubuntu-latest
    steps:
      - name: test login
        uses: azure/login@v1
        with: 
          client-id: ${{secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{secrets.AZURE_TENANT_ID}} 
          subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
    # Run az commands to confirm sub access

      - name: 'Run az commands'
        run: |
          az account show
      - name: checkout
        uses: actions/checkout@v3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
      - name: terraform
        working-directory: ./lz01
        
        env:
          STORAGE_ACCOUNT : ${{secrets.STORAGE_ACCOUNT}}
          CONTAINER_NAME: ${{secrets.CONTAINER_NAME}}
          RESOURCE_GROUP_NAME: ${{secrets.STORAGE_RESOURCE_GROUP_NAME}}
          ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP_NAME"
      - name: Terraform plan
        id: plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform plan -no-color
        working-directory: ./lz01
            


