name: login test
on: [push]
# defaults:
#   run:
#     working-directory: ./lz01
permissions: 
  id-token: write
  contents: read
  deployments: write
jobs:
  
  configure-env01:
    runs-on: ubuntu-latest
    steps:
      # - name: test login
      #   uses: azure/login@v1
      #   with: 
      #     client-id: ${{secrets.AZURE_CLIENT_ID}}
      #     tenant-id: ${{secrets.AZURE_TENANT_ID}} 
      #     subscription-id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      - name: checkout
        uses: actions/checkout@v3
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
      - name: az sp login
        run: 
          az login --service-principal -u ${{secrets.AZURE_CLIENT_ID}} -p ${{secrets.AZURE_CLIENT_SECRET}} --tenant ${{secrets.AZURE_TENANT_ID}} 
      - name: terraform
        run: terraform init
        working-directory: ./lz01
          
        
